

services:
  postgres:
    image: postgres:14.5
#    volumes:
#      - "/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock"
#      - "dbdata:/var/lib/postgresql/data"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orders
    ports:
      - 5432:5432

  orders_parser:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - postgres
    depends_on:
      - postgres